spring:
  application:
    name: ter-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/v4h_preservation
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jackson:
    time-zone: America/Sao_Paulo

logging:
  level:
    ROOT: INFO

server:
  port: 3030

#Actuator setup.
management:
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "env, metrics, health, info"
        
#Envirements variables
environments:
  dev:
    PUBLIC_KEY_NAME: pkey.der
    ACTUAL_STORAGE_PATH: ./keys
    SALT: jajaba
